[env:xiaoblesense_adafruit]
platform = https://github.com/maxgerhardt/platform-nordicnrf52
board = xiaoblesense_adafruit
framework = arduino
build_flags = -DTRANSPORT_BLE=1

lib_deps =
    seeed-studio/Seeed Arduino LSM6DS3@^2.0.4

monitor_speed = 115200
upload_protocol = nrfutil

[env:xiaoblesense_usb]
extends = env:xiaoblesense_adafruit
build_flags = -DTRANSPORT_USB=1

[env:xiaoblesense_dual]
extends = env:xiaoblesense_adafruit
build_flags =
    -DTRANSPORT_BLE=1
    -DTRANSPORT_USB=1
