[env:xiaoblesense_adafruit]
platform = https://github.com/maxgerhardt/platform-nordicnrf52
board = xiaoblesense_adafruit
framework = arduino

lib_deps =
    seeed-studio/Seeed Arduino LSM6DS3@^2.0.4

monitor_speed = 115200
upload_protocol = nrfutil
