[env:nano33ble]
platform = nordicnrf52
board = nano33ble
framework = arduino

lib_deps =
    arduino-libraries/ArduinoBLE
    arduino-libraries/Arduino_BMI270_BMM150

monitor_speed = 115200

[env:nano33ble_viewer]
extends = env:nano33ble
build_flags = -DNANO_USB_ORIENTATION_VIEWER
lib_deps =
    ${env:nano33ble.lib_deps}
